CREATE TABLE IF NOT EXISTS `geocodes` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `query` varchar(100),
  `lat` DOUBLE DEFAULT 0,
  `lng` DOUBLE DEFAULT 0,
  `date_updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()
) ENGINE=INNODB;
