CREATE TABLE IF NOT EXISTS `listings` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `url` varchar(190),
  `site` varchar(50),
  `ownership_type` int,
  `housing_type` varchar(50),
  `street_address` varchar(50),
  `zip` varchar(10),
	`suburb` varchar(30),
  `city` varchar(30),
  `price` float(20),
  `country` varchar(50),
  `agency` varchar(100),
  `description` text,
  `living_space_m2` float(10),
  `layout` varchar(100),
  `total_space_m2` float(10),
  `availability` varchar(50),
  `build_year` int(4),
  `floor` int,
  `floor_count` int,
  `floor_max` int,
  `additional_info` text,
  `condition` varchar(50),
	`flags` bit(8) NOT NULL DEFAULT 0,
  `date_added` timestamp NOT NULL DEFAULT "0000-00-00 00:00:00",
  `date_updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()
) ENGINE=INNODB;
